version: '3.5'

services:
  worker:
    image: omnidialer_worker
    build:
      context: ./workers/handle-campaign/src
    tty: true
    stdin_open: true
    environment:
      - ASTERISK_HOST=${ASTERISK_HOST}
      - ASTERISK_PORT=${ASTERISK_PORT}
      - ASTERISK_USER=${ASTERISK_USER}
      - ASTERISK_PASS=${ASTERISK_PASS}
      - ASTERISK_APP=${ASTERISK_APP}
      - REDIS_OML_SERVER=${REDIS_OML_SERVER}
      - REDIS_OML_PORT=${REDIS_OML_PORT}
      - REDIS_DIALER_SERVER=${REDIS_DIALER_SERVER}
      - REDIS_DIALER_PORT=${REDIS_DIALER_PORT}
      - POSTGRES_OML_PASSWORD=${POSTGRES_OML_PASSWORD}
      - POSTGRES_OML_SERVER=${POSTGRES_OML_SERVER}
      - POSTGRES_OML_PORT=${POSTGRES_OML_PORT}
      - POSTGRES_DIALER_PASSWORD=${POSTGRES_DIALER_PASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - TZ=${TZ}
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - GEARMAN_JOBS=${GEARMAN_JOBS}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
      - DIALER_ACD_HOST=${DIALER_ACD_HOST}
      - TIME_BETWEEN_CALLS=${TIME_BETWEEN_CALLS}
