networks:
  omnileads:
    name: ${NETWORK}
    external: true



volumes:

  dialer-postgresql:

services:

  dialer-api:
    build:
      target: run
      context: ./interface/src
    image: ${API_IMG}
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:1440/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    ports:
      - ${DIALER_API_EXT_BIND_IP:-0.0.0.0}:${DIALER_API_EXT_PORT:-1440}:1440/tcp
    networks:
      - omnileads
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - WEBSOCKET_SERVER=${WEBSOCKET_SERVER}

  scheduler-api:
    build:
      context: ./scheduler/src
    image: ${SCHEDULER_IMG}
    ports:
      - ${DIALER_SCHEDULER_EXT_BIND_IP:-0.0.0.0}:${DIALER_SCHEDULER_EXT_PORT:-1441}:1441/tcp
    networks:
      - omnileads
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - REDIS_DIALER_SERVER=${REDIS_DIALER_SERVER}
      - REDIS_DIALER_PORT=${REDIS_DIALER_PORT}
      - TZ=${TZ}

  listener:
    build:
      context: ./websocket_ari/src
    image: ${LISTENER_IMG}
    networks:
      - omnileads
    tty: true
    stdin_open: true
    environment:
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - ASTERISK_APP_DIALER=call_manager_dialer
      - TZ=${TZ}
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
    depends_on:
      dialer-postgresql:
        condition: service_healthy
        required: true
      start-campaign:
        condition: service_started
        required: true
      dialer-acd:
        condition: service_started
        required: true

  start-campaign:
    build:
      context: ./workers/handle-campaign/src
    image: ${WORKER_IMG}
    networks:
      - omnileads
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=start-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    depends_on:
      - dialer-postgresql

  process-contact-worker:
    image: ${WORKER_IMG}
    deploy:
      replicas: ${PROCESS_CONTACT_REPLICAS}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=process-contact
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    depends_on:
      - dialer-postgresql
    networks:
      - omnileads

  process-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    deploy:
      replicas: ${PROCESS_CAMPAIGN_REPLICAS}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=process-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
      - TIME_BETWEEN_CALLS=${TIME_BETWEEN_CALLS}
    networks:
      - omnileads

  create-campaign-worker:
    image: ${WORKER_IMG}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=create-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  resume-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=resume-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  edit-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=edit-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  stop-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=stop-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  pause-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=pause-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  delete-campaign-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=delete-campaign
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  process-event-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    deploy:
        replicas: ${PROCESS_EVENT_REPLICAS}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    environment:
      - GEARMAN_JOBS=process-event
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  send-reports-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=send-reports
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  add-incidence-rule-disposition-worker:
    image: ${WORKER_IMG}
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=add-incidence-rule-disposition
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  change-database-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=change-database
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  create-incidence-rule-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=create-incidence-rule
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  delete-incidence-rule-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=delete-incidence-rule
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  update-incidence-rule-worker:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=update-incidence-rule
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  schedule-agenda:
    image: ${WORKER_IMG}
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=schedule-agenda
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  render-template:
    image: ${WORKER_IMG}
    env_file: .env
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=render-template
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  manage-dialer:
    image: ${WORKER_IMG}
    stop_signal: SIGINT
    tty: true
    stdin_open: true
    depends_on:
      - dialer-postgresql
    environment:
      - GEARMAN_JOBS=manage-dialer
      - GEARMAN_JOB_SERVERS=${GEARMAN_JOB_SERVERS}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
      - CAPS=${DIALER_CAPS}
      - DIALER_ACD_HOST=pstn_gateway
      - POSTGRES_OML_SERVER=${PGHOST}
      - POSTGRES_OML_PORT=${PGPORT}
      - POSTGRES_OML_USER=${PGUSER}
      - POSTGRES_OML_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_SERVER=${POSTGRES_DIALER_SERVER}
      - POSTGRES_DIALER_PORT=${POSTGRES_DIALER_PORT}
      - POSTGRES_DIALER_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_DIALER_PASSWORD=${PGPASSWORD}
      - POSTGRES_DIALER_DB=${POSTGRES_DIALER_DB}
      - REDIS_OML_SERVER=${REDIS_HOSTNAME}
      - REDIS_OML_PORT=${REDIS_PORT}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - PYTHON_LOGLEVEL=${PYTHON_LOGLEVEL}
    networks:
      - omnileads

  dialer-acd:
    build:
      context: ./asterisk/
    image: ${ASTERISK_IMG}
    environment:
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - OMLACD_SIP_SERVER=${OMLACD_SIP_SERVER}
      - PSTNGW_REGISTER=${PSTNGW_REGISTER}
      - PSTNGW_SIP_AUTH=${PSTNGW_SIP_AUTH}
      - PSTNGW_SIP_USER=${PSTNGW_SIP_USER}
      - PSTNGW_SIP_PASS=${PSTNGW_SIP_PASS}
    dns: 8.8.8.8
    networks:
      omnileads:
        ipv4_address: ${DIALER_ASTERISK_IPV4}
    privileged: true
    restart: on-failure
    stop_grace_period: 30s
    working_dir: /etc/asterisk

  dialer-dialplan:
    build:
      target: run
      context: ./dialplan/
    image: ${DIALPLAN_IMG}
    depends_on:
      - dialer-acd
    environment:
      - TZ=${TZ}
      - GEARMAN_HOST=${GEARMAN_HOSTNAME}
      - REDIS_DIALER_SERVER=${REDIS_HOSTNAME}
      - REDIS_DIALER_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DIALER_DB}
      - ASTERISK_HOST=${ASTERISK_DIALER_HOSTNAME}
      - ASTERISK_PORT=${ASTERISK_DIALER_ARI_PORT}
      - ASTERISK_USER=${AMI_USER}
      - ASTERISK_PASS=${AMI_PASSWORD}
      - ASTERISK_APP=call_manager
    restart: on-failure
    stop_grace_period: 30s
    networks:
      - omnileads

  dialer-postgresql:
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${POSTGRES_DIALER_USER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${POSTGRES_DIALER_DB}
      - PGPORT=5433
    image: ${POSTGRES_IMG}
    networks:
      - omnileads
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DIALER_USER} -d ${POSTGRES_DIALER_DB} -q"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - dialer-postgresql:/var/lib/postgresql/data
      - ../omnidialer.sql:/docker-entrypoint-initdb.d/init.sql
